(defun isogramp (phrase)
  (let ((letters '())
        (is-isogram t)
        (clean-phrase (downcase phrase)))
    (seq-doseq (char clean-phrase)
      (when (and (>= char ?a) (<= char ?z))
        (if (member char letters)
            (setq is-isogram nil)
          (push char letters))))
    is-isogram))
