(defun armstrong-p (n)
  (let* ((str (number-to-string n))
         (len (length str))
         (sum 0))
    (dotimes (i len)
      (let* ((char (elt str i))
             (digit (- char ?0)))
        (setq sum (+ sum (expt digit len)))))
    (= sum n)))
